services:
  - type: web
    name: oxford-word-boxes
    runtime: static
    buildCommand: "bash build.sh"
    staticPublishPath: .
    headers:
      - path: "/*.js"
        name: Content-Type
        value: application/javascript; charset=utf-8
      - path: "/*.css"
        name: Content-Type
        value: text/css; charset=utf-8
    envVars:
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
