services:
  - type: web
    name: oxford-word-boxes
    runtime: static
    buildCommand: "true"
    staticPublishPath: .
    headers:
      - path: "/*.js"
        name: Content-Type
        value: application/javascript; charset=utf-8
      - path: "/*.css"
        name: Content-Type
        value: text/css; charset=utf-8
